<template>
  <div class="menu">
    <ul>
      <li>
        <a
          title=""
          href="/blogs"
        >List</a>
      </li>
      <li>
        <a
          title=""
          href="/blogs/create"
        >New</a>
      </li>
      <li>
        <a
          title=""
          href="/blogs/search"
        >Search</a>
      </li>
      <li>
        <a
          title=""
          href="/blogs/edit"
        >Edit</a>
      </li>
    </ul>
  </div>
</template>